name: Manage AWS Parameter Store

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Action"
        required: true
        default: list
        type: choice
        options:
          - list
          - create
          - update
          - delete
      parameter_name:
        description: "Parameter name"
        type: string
        required: false
      parameter_value:
        description: "Parameter value"
        type: string
        required: false
      parameter_type:
        description: "Parameter type"
        type: choice
        required: false
        default: String
        options:
          - String
          - SecureString
          - StringList

jobs:
  build:
    environment: dev
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: List Parameters
        if: ${{ github.event.inputs.action == 'list' }}
        run: |
          aws ssm describe-parameters --output json
      
      - name: Create Parameter
        if: ${{ github.event.inputs.action == 'create' }}
        run: |
          aws ssm put-parameter \
            --name "${{ github.event.inputs.parameter_name }}" \
            --value "${{ github.event.inputs.parameter_value }}" \
            --type "${{ github.event.inputs.parameter_type }}" \
            --no-overwrite

      - name: Update Parameter
        if: ${{ github.event.inputs.action == 'update' }}
        run: |
          aws ssm put-parameter \
            --name "${{ github.event.inputs.parameter_name }}" \
            --value "${{ github.event.inputs.parameter_value }}" \
            --type "${{ github.event.inputs.parameter_type }}" \
            --overwrite

      - name: Delete Parameter
        if: ${{ github.event.inputs.action == 'delete' }}
        run: |
          aws ssm delete-parameter --name "${{ github.event.inputs.parameter_name }}"